[tools]
golangci-lint = "2.7.0"
"vfox-pulumi:pulumi/pulumi-std" = "2.2.0"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "1.2.4"
"vfox-pulumi:pulumi/pulumi-random" = "4.18.5"
"vfox-pulumi:pulumi/pulumi-aws" = "7.16.0"
"vfox-pulumi:pulumi/pulumi-gcp" = "9.9.0"
"vfox-pulumi:pulumi/pulumi-azure" = "6.31.0"
